DS3231
const std::array< std::string, 7 > DS3231::WEEKDAYS
Referenced by getDateTime, getTime, unixToDateTime.
i2c_inst_t* DS3231::i2c
Referenced by DS3231, getDateTime, getTime, setTime.
uint8_t DS3231::address
Referenced by DS3231, getDateTime, getTime, setTime.
int16_t DS3231::timezoneOffset
Referenced by getDateTimeLocal, getTimeUnixLocal, getTimezoneOffset, setTimezoneOffset.
uint32_t DS3231::syncInterval
Referenced by getClockSyncInterval, needsSync, setClockSyncInterval.
uint32_t DS3231::lastSyncTime
Referenced by getLastSyncTime, needsSync, setLastSyncTime.
float DS3231::clockDrift
Referenced by getClockDrift, needsSync, setClockDrift.
uint8_t DS3231::RTC_REGISTER
Referenced by getDateTime, getTime, setTime.
DS3231::DS3231(i2c_inst_t *i2c, uint8_t address=0x68)
References address, i2c.
bool DS3231::setTime(uint8_t sec, uint8_t min, uint8_t hour, uint8_t weekday, uint8_t day, uint8_t month, uint16_t year)
References address, bin2bcd, buffer, i2c, RTC_REGISTER.
Referenced by setTimeUnix.
bool DS3231::getTime(uint8_t &sec, uint8_t &min, uint8_t &hour, std::string &weekday, uint8_t &day, uint8_t &month, uint16_t &year)
References address, bcd2bin, buffer, i2c, RTC_REGISTER, WEEKDAYS.
Referenced by getTimeString.
std::string DS3231::getTimeString()
References getTime, preZero.
bool DS3231::setTimeUnix(uint32_t unixTime)
References DateTime::day, DateTime::hour, DateTime::minute, DateTime::month, DateTime::second, setTime, unixToDateTime, DateTime::year.
uint32_t DS3231::getTimeUnix()
References dateTimeToUnix, getDateTime.
Referenced by getTimeUnixLocal, needsSync.
DateTime DS3231::getDateTime()
References address, bcd2bin, buffer, DateTime::day, DateTime::hour, i2c, DateTime::minute, DateTime::month, RTC_REGISTER, DateTime::second, DateTime::weekday, WEEKDAYS, DateTime::year.
Referenced by getDateTimeLocal, getTimeInteger, getTimeUnix.
uint64_t DS3231::getTimeInteger()
References DateTime::day, getDateTime, DateTime::hour, DateTime::minute, DateTime::month, DateTime::second, DateTime::year.
void DS3231::setTimezoneOffset(int16_t offsetMinutes)
References timezoneOffset.
int16_t DS3231::getTimezoneOffset() const
References timezoneOffset.
uint32_t DS3231::getTimeUnixLocal()
References getTimeUnix, timezoneOffset.
DateTime DS3231::getDateTimeLocal()
References applyTimezone, getDateTime, timezoneOffset.
void DS3231::setClockSyncInterval(uint32_t intervalSeconds)
References syncInterval.
uint32_t DS3231::getClockSyncInterval() const
References syncInterval.
void DS3231::setLastSyncTime(uint32_t unixTime)
References lastSyncTime.
uint32_t DS3231::getLastSyncTime() const
References lastSyncTime.
void DS3231::setClockDrift(float ppmDrift)
References clockDrift.
float DS3231::getClockDrift() const
References clockDrift.
bool DS3231::needsSync()
References clockDrift, getTimeUnix, lastSyncTime, syncInterval.
uint8_t DS3231::bcd2bin(uint8_t val)
Referenced by getDateTime, getTime.
uint8_t DS3231::bin2bcd(uint8_t val)
Referenced by setTime.
std::string DS3231::preZero(uint8_t val)
Referenced by getTimeString.
DateTime DS3231::applyTimezone(const DateTime &utc, int16_t offsetMinutes)
References dateTimeToUnix, unixToDateTime.
Referenced by getDateTimeLocal.
uint32_t DS3231::dateTimeToUnix(const DateTime &dt)
References DateTime::day, DateTime::hour, DateTime::minute, DateTime::month, DateTime::second, DateTime::year.
Referenced by applyTimezone, getTimeUnix.
DateTime DS3231::unixToDateTime(uint32_t unixTime)
References DateTime::day, DateTime::hour, DateTime::minute, DateTime::month, DateTime::second, DateTime::weekday, WEEKDAYS, DateTime::year.
Referenced by applyTimezone, setTimeUnix.