LoRaClass
spi_inst_t* LoRaClass::_spi
Referenced by LoRaClass, setSPI.
int LoRaClass::_ss
Referenced by begin, LoRaClass, setPins, singleTransfer.
int LoRaClass::_reset
Referenced by begin, LoRaClass, setPins.
int LoRaClass::_dio0
Referenced by LoRaClass, onCadDone, onReceive, onTxDone, setPins.
long LoRaClass::_frequency
Referenced by LoRaClass, packetRssi, rssi, setFrequency.
int LoRaClass::_packetIndex
Referenced by available, handleDio0Rise, LoRaClass, parsePacket, read.
int LoRaClass::_implicitHeaderMode
Referenced by explicitHeaderMode, handleDio0Rise, implicitHeaderMode, LoRaClass, parsePacket.
void(* LoRaClass::_onReceive) (int))(int)
Referenced by handleDio0Rise, LoRaClass, onReceive.
void(* LoRaClass::_onCadDone) (bool))(bool)
Referenced by handleDio0Rise, LoRaClass, onCadDone.
void(* LoRaClass::_onTxDone) ())()
Referenced by endPacket, handleDio0Rise, LoRaClass, onTxDone.
LoRaClass::LoRaClass()
References _dio0, _frequency, _implicitHeaderMode, _onCadDone, _onReceive, _onTxDone, _packetIndex, _reset, _spi, _ss, LORA_DEFAULT_DIO0_PIN, LORA_DEFAULT_RESET_PIN, LORA_DEFAULT_SS_PIN, SPI_PORT.
int LoRaClass::begin(long frequency)
References _reset, _ss, idle, LORA_DEFAULT_SPI_FREQUENCY, readRegister, REG_FIFO_RX_BASE_ADDR, REG_FIFO_TX_BASE_ADDR, REG_LNA, REG_MODEM_CONFIG_3, REG_VERSION, setFrequency, setTxPower, sleep, SPI_PORT, SX1278_CS, SX1278_MISO, SX1278_MOSI, SX1278_SCK, writeRegister.
void LoRaClass::end()
References sleep, SPI_PORT.
int LoRaClass::beginPacket(int implicitHeader=false)
References explicitHeaderMode, idle, implicitHeaderMode, isTransmitting, REG_FIFO_ADDR_PTR, REG_PAYLOAD_LENGTH, writeRegister.
int LoRaClass::endPacket(bool async=false)
References _onTxDone, IRQ_TX_DONE_MASK, MODE_LONG_RANGE_MODE, MODE_TX, readRegister, REG_DIO_MAPPING_1, REG_IRQ_FLAGS, REG_OP_MODE, writeRegister.
int LoRaClass::parsePacket(int size=0)
References _implicitHeaderMode, _packetIndex, explicitHeaderMode, idle, implicitHeaderMode, IRQ_PAYLOAD_CRC_ERROR_MASK, IRQ_RX_DONE_MASK, MODE_LONG_RANGE_MODE, MODE_RX_SINGLE, readRegister, REG_FIFO_ADDR_PTR, REG_FIFO_RX_CURRENT_ADDR, REG_IRQ_FLAGS, REG_OP_MODE, REG_PAYLOAD_LENGTH, REG_RX_NB_BYTES, writeRegister.
int LoRaClass::packetRssi()
References _frequency, readRegister, REG_PKT_RSSI_VALUE, RF_MID_BAND_THRESHOLD, RSSI_OFFSET_HF_PORT, RSSI_OFFSET_LF_PORT.
float LoRaClass::packetSnr()
References readRegister, REG_PKT_SNR_VALUE.
long LoRaClass::packetFrequencyError()
References getSignalBandwidth, readRegister, REG_FREQ_ERROR_LSB, REG_FREQ_ERROR_MID, REG_FREQ_ERROR_MSB.
int LoRaClass::rssi()
References _frequency, readRegister, REG_RSSI_VALUE, RF_MID_BAND_THRESHOLD, RSSI_OFFSET_HF_PORT, RSSI_OFFSET_LF_PORT.
size_t LoRaClass::write(uint8_t byte)
References write.
Referenced by write.
size_t LoRaClass::write(const uint8_t *buffer, size_t size)
References buffer, MAX_PKT_LENGTH, readRegister, REG_FIFO, REG_PAYLOAD_LENGTH, writeRegister.
int LoRaClass::available()
References _packetIndex, readRegister, REG_RX_NB_BYTES.
Referenced by peek, read.
int LoRaClass::read()
References _packetIndex, available, readRegister, REG_FIFO.
int LoRaClass::peek()
References available, readRegister, REG_FIFO, REG_FIFO_ADDR_PTR, writeRegister.
void LoRaClass::flush()
void LoRaClass::onCadDone(void(*callback)(bool))
References _dio0, _onCadDone, onDio0Rise.
void LoRaClass::onReceive(void(*callback)(int))
References _dio0, _onReceive, onDio0Rise.
void LoRaClass::onTxDone(void(*callback)())
References _dio0, _onTxDone, onDio0Rise.
void LoRaClass::receive(int size=0)
References explicitHeaderMode, implicitHeaderMode, MODE_LONG_RANGE_MODE, MODE_RX_CONTINUOUS, REG_DIO_MAPPING_1, REG_OP_MODE, REG_PAYLOAD_LENGTH, writeRegister.
void LoRaClass::channelActivityDetection(void)
References MODE_CAD, MODE_LONG_RANGE_MODE, REG_DIO_MAPPING_1, REG_OP_MODE, writeRegister.
void LoRaClass::idle()
References MODE_LONG_RANGE_MODE, MODE_STDBY, REG_OP_MODE, writeRegister.
Referenced by begin, beginPacket, parsePacket, setGain.
void LoRaClass::sleep()
References MODE_LONG_RANGE_MODE, MODE_SLEEP, REG_OP_MODE, writeRegister.
Referenced by begin, end.
void LoRaClass::setTxPower(int level, int outputPin=PA_OUTPUT_PA_BOOST_PIN)
References PA_BOOST, PA_OUTPUT_RFO_PIN, REG_PA_CONFIG, REG_PA_DAC, setOCP, writeRegister.
Referenced by begin.
void LoRaClass::setFrequency(long frequency)
References _frequency, REG_FRF_LSB, REG_FRF_MID, REG_FRF_MSB, writeRegister.
Referenced by begin.
void LoRaClass::setSpreadingFactor(int sf)
References readRegister, REG_DETECTION_OPTIMIZE, REG_DETECTION_THRESHOLD, REG_MODEM_CONFIG_2, setLdoFlag, writeRegister.
void LoRaClass::setSignalBandwidth(long sbw)
References readRegister, REG_MODEM_CONFIG_1, setLdoFlag, writeRegister.
void LoRaClass::setCodingRate4(int denominator)
References readRegister, REG_MODEM_CONFIG_1, writeRegister.
void LoRaClass::setPreambleLength(long length)
References REG_PREAMBLE_LSB, REG_PREAMBLE_MSB, writeRegister.
void LoRaClass::setSyncWord(int sw)
References REG_SYNC_WORD, writeRegister.
void LoRaClass::enableCrc()
References readRegister, REG_MODEM_CONFIG_2, writeRegister.
Referenced by crc.
void LoRaClass::disableCrc()
References readRegister, REG_MODEM_CONFIG_2, writeRegister.
Referenced by noCrc.
void LoRaClass::enableInvertIQ()
References REG_INVERTIQ, REG_INVERTIQ2, writeRegister.
void LoRaClass::disableInvertIQ()
References REG_INVERTIQ, REG_INVERTIQ2, writeRegister.
void LoRaClass::setOCP(uint8_t mA)
References REG_OCP, writeRegister.
Referenced by setTxPower.
void LoRaClass::setGain(uint8_t gain)
References idle, readRegister, REG_LNA, REG_MODEM_CONFIG_3, writeRegister.
void LoRaClass::crc()
References enableCrc.
void LoRaClass::noCrc()
References disableCrc.
uint8_t LoRaClass::random()
References readRegister, REG_RSSI_WIDEBAND.
void LoRaClass::setPins(int ss=LORA_DEFAULT_SS_PIN, int reset=LORA_DEFAULT_RESET_PIN, int dio0=LORA_DEFAULT_DIO0_PIN)
References _dio0, _reset, _ss.
void LoRaClass::setSPI(spi_inst_t &spi)
References _spi.
void LoRaClass::setSPIFrequency(uint32_t frequency)
References SPI_PORT.
void LoRaClass::dumpRegisters()
References readRegister.
void LoRaClass::explicitHeaderMode()
References _implicitHeaderMode, readRegister, REG_MODEM_CONFIG_1, writeRegister.
Referenced by beginPacket, parsePacket, receive.
void LoRaClass::implicitHeaderMode()
References _implicitHeaderMode, readRegister, REG_MODEM_CONFIG_1, writeRegister.
Referenced by beginPacket, parsePacket, receive.
void LoRaClass::handleDio0Rise()
References _implicitHeaderMode, _onCadDone, _onReceive, _onTxDone, _packetIndex, IRQ_CAD_DETECTED_MASK, IRQ_CAD_DONE_MASK, IRQ_PAYLOAD_CRC_ERROR_MASK, IRQ_RX_DONE_MASK, IRQ_TX_DONE_MASK, readRegister, REG_FIFO_ADDR_PTR, REG_FIFO_RX_CURRENT_ADDR, REG_IRQ_FLAGS, REG_PAYLOAD_LENGTH, REG_RX_NB_BYTES, writeRegister.
bool LoRaClass::isTransmitting()
References IRQ_TX_DONE_MASK, MODE_TX, readRegister, REG_IRQ_FLAGS, REG_OP_MODE, writeRegister.
Referenced by beginPacket.
int LoRaClass::getSpreadingFactor()
References readRegister, REG_MODEM_CONFIG_2.
Referenced by setLdoFlag.
long LoRaClass::getSignalBandwidth()
References readRegister, REG_MODEM_CONFIG_1.
Referenced by packetFrequencyError, setLdoFlag.
void LoRaClass::setLdoFlag()
References getSignalBandwidth, getSpreadingFactor, readRegister, REG_MODEM_CONFIG_3, writeRegister.
Referenced by setSignalBandwidth, setSpreadingFactor.
uint8_t LoRaClass::readRegister(uint8_t address)
References singleTransfer.
Referenced by available, begin, disableCrc, dumpRegisters, enableCrc, endPacket, explicitHeaderMode, getSignalBandwidth, getSpreadingFactor, handleDio0Rise, implicitHeaderMode, isTransmitting, packetFrequencyError, packetRssi, packetSnr, parsePacket, peek, random, read, rssi, setCodingRate4, setGain, setLdoFlag, setSignalBandwidth, setSpreadingFactor, write.
void LoRaClass::writeRegister(uint8_t address, uint8_t value)
References singleTransfer.
Referenced by begin, beginPacket, channelActivityDetection, disableCrc, disableInvertIQ, enableCrc, enableInvertIQ, endPacket, explicitHeaderMode, handleDio0Rise, idle, implicitHeaderMode, isTransmitting, parsePacket, peek, receive, setCodingRate4, setFrequency, setGain, setLdoFlag, setOCP, setPreambleLength, setSignalBandwidth, setSpreadingFactor, setSyncWord, setTxPower, sleep, write.
uint8_t LoRaClass::singleTransfer(uint8_t address, uint8_t value)
References _ss, SPI_PORT.
Referenced by readRegister, writeRegister.
void LoRaClass::onDio0Rise(uint, uint32_t)
References LoRa.
Referenced by onCadDone, onReceive, onTxDone.