PowerManager
float PowerManager::SOLAR_CURRENT_THRESHOLD
Referenced by isSolarActive.
float PowerManager::USB_CURRENT_THRESHOLD
Referenced by isUSBConnected.
float PowerManager::VOLTAGE_LOW_THRESHOLD
Referenced by checkPowerEvents.
float PowerManager::VOLTAGE_OVERCHARGE_THRESHOLD
Referenced by checkPowerEvents.
float PowerManager::FALL_RATE_THRESHOLD
int PowerManager::FALLING_TREND_REQUIRED
INA3221 PowerManager::ina3221
Referenced by configure, getCurrentChargeSolar, getCurrentChargeTotal, getCurrentChargeUSB, getCurrentDraw, getVoltage5V, getVoltageBattery, initialize, PowerManager, readIDs.
bool PowerManager::initialized
Referenced by configure, getCurrentChargeSolar, getCurrentChargeTotal, getCurrentChargeUSB, getCurrentDraw, getVoltage5V, getVoltageBattery, initialize, isSolarActive, isUSBConnected, readIDs.
bool PowerManager::solarActive
bool PowerManager::usbConnected
PowerManager::PowerManager(i2c_inst_t *i2c)
References ina3221, INA3221_ADDR40_GND.
bool PowerManager::initialize()
References ina3221, initialized.
std::string PowerManager::readIDs()
References ina3221, initialized.
float PowerManager::getCurrentChargeSolar()
References ina3221, INA3221_CH3, initialized.
Referenced by isSolarActive.
float PowerManager::getCurrentChargeUSB()
References ina3221, INA3221_CH1, initialized.
Referenced by isUSBConnected.
float PowerManager::getCurrentChargeTotal()
References ina3221, INA3221_CH1, INA3221_CH3, initialized.
float PowerManager::getCurrentDraw()
References ina3221, INA3221_CH2, initialized.
float PowerManager::getVoltageBattery()
References ina3221, INA3221_CH1, initialized.
float PowerManager::getVoltage5V()
References ina3221, INA3221_CH2, initialized.
Referenced by checkPowerEvents.
void PowerManager::configure(const std::map< std::string, std::string > &config)
References ina3221, INA3221_REG_CONF_AVG_1, INA3221_REG_CONF_AVG_16, INA3221_REG_CONF_AVG_4, initialized.
bool PowerManager::isSolarActive()
References getCurrentChargeSolar, initialized, SOLAR_CURRENT_THRESHOLD.
Referenced by checkPowerEvents.
bool PowerManager::isUSBConnected()
References getCurrentChargeUSB, initialized, USB_CURRENT_THRESHOLD.
Referenced by checkPowerEvents.