BH1750
Mode
uint8_t BH1750::_i2c_addr
Referenced by begin, BH1750, readLightLevel, write8.
BH1750::BH1750(uint8_t addr=0x23)
References _i2c_addr.
bool BH1750::begin(Mode mode=Mode::CONTINUOUS_HIGH_RES_MODE)
References _i2c_addr, configure, POWER_ON, RESET, write8.
void BH1750::configure(Mode mode)
References CONTINUOUS_HIGH_RES_MODE, CONTINUOUS_HIGH_RES_MODE_2, CONTINUOUS_LOW_RES_MODE, ONE_TIME_HIGH_RES_MODE, ONE_TIME_HIGH_RES_MODE_2, ONE_TIME_LOW_RES_MODE, write8.
Referenced by begin.
float BH1750::readLightLevel()
References _i2c_addr, buffer.
void BH1750::write8(uint8_t data)
References _i2c_addr.
Referenced by begin, configure.