EventEmitter
static void EventEmitter::emit(EventGroup group, T event)
References event, eventManager, group.
Referenced by checkPowerEvents, handleEnableGPSTransparentMode, handleGPSPowerStatus, handleTime, initializeRadio.