EventManager
EventLog EventManager::events[EVENT_BUFFER_SIZE][EVENT_BUFFER_SIZE]
Referenced by getEvent, logEvent.
size_t EventManager::eventCount
Referenced by EventManager, getEvent, getEventCount, logEvent.
size_t EventManager::writeIndex
Referenced by EventManager, getEvent, logEvent.
mutex_t EventManager::eventMutex
Referenced by EventManager, logEvent.
volatile uint16_t EventManager::nextEventId
Referenced by EventManager, logEvent.
bool EventManager::needsPersistence
Referenced by EventManager, logEvent, EventManagerImpl::saveToStorage.
EventManager::EventManager()
References eventCount, eventMutex, needsPersistence, nextEventId, writeIndex.
virtual EventManager::~EventManager()=default
virtual void EventManager::init()
References loadFromStorage.
Referenced by EventManagerImpl::EventManagerImpl.
void EventManager::logEvent(uint8_t group, uint8_t event)
References event, EventLog::event, EVENT_BUFFER_SIZE, eventCount, eventMutex, events, EventLog::group, group, EventLog::id, needsPersistence, nextEventId, POWER, POWER_FALLING, saveToStorage, systemClock, EventLog::timestamp, EventLog::toString, uartPrint, writeIndex.
const EventLog & EventManager::getEvent(size_t index) const
References EVENT_BUFFER_SIZE, eventCount, events, writeIndex.
size_t EventManager::getEventCount() const
References eventCount.
virtual bool EventManager::saveToStorage()=0
Referenced by logEvent.
virtual bool EventManager::loadFromStorage()=0
Referenced by init.