INA3221
i2c_inst_t* INA3221::_i2c
Referenced by INA3221.
ina3221_addr_t INA3221::_i2c_addr
Referenced by _read, _write, INA3221, setAddr.
uint32_t INA3221::_shuntRes[INA3221_CH_NUM][INA3221_CH_NUM]
Referenced by begin, estimateOffsetVoltage, getCurrent, getCurrent_mA, getCurrentCompensated, getCurrentCompensated_mA.
uint32_t INA3221::_filterRes[INA3221_CH_NUM][INA3221_CH_NUM]
Referenced by begin, estimateOffsetVoltage.
masken_reg_t INA3221::_masken_reg
void INA3221::_read(ina3221_reg_t reg, uint16_t *val)
References _i2c_addr, MAIN_I2C_PORT.
Referenced by getDieID, getManufID, getReg, getShuntVoltage, getVoltage, reset, setAveragingMode, setBusConversionTime, setBusMeasDisable, setBusMeasEnable, setModeContinious, setModePowerDown, setModeTriggered, setShuntConversionTime, setShuntMeasDisable, setShuntMeasEnable.
void INA3221::_write(ina3221_reg_t reg, uint16_t *val)
References _i2c_addr, MAIN_I2C_PORT.
Referenced by reset, setAveragingMode, setBusConversionTime, setBusMeasDisable, setBusMeasEnable, setModeContinious, setModePowerDown, setModeTriggered, setShuntConversionTime, setShuntMeasDisable, setShuntMeasEnable.
INA3221::INA3221(ina3221_addr_t addr, i2c_inst_t *i2c)
References _i2c, _i2c_addr.
bool INA3221::begin()
References _filterRes, _shuntRes, getDieID, getManufID, uartPrint.
void INA3221::setShuntRes(uint32_t res_ch1, uint32_t res_ch2, uint32_t res_ch3)
void INA3221::setFilterRes(uint32_t res_ch1, uint32_t res_ch2, uint32_t res_ch3)
void INA3221::setAddr(ina3221_addr_t addr)
References _i2c_addr.
uint16_t INA3221::getReg(ina3221_reg_t reg)
References _read.
void INA3221::reset()
References _read, _write, INA3221_REG_CONF, INA3221::conf_reg_t::reset.
void INA3221::setModePowerDown()
References _read, _write, INA3221_REG_CONF, INA3221::conf_reg_t::mode_bus_en, INA3221::conf_reg_t::mode_continious_en.
void INA3221::setModeContinious()
References _read, _write, INA3221_REG_CONF, INA3221::conf_reg_t::mode_continious_en.
void INA3221::setModeTriggered()
References _read, _write, INA3221_REG_CONF, INA3221::conf_reg_t::mode_continious_en.
void INA3221::setShuntMeasEnable()
References _read, _write, INA3221_REG_CONF, INA3221::conf_reg_t::mode_shunt_en.
void INA3221::setShuntMeasDisable()
References _read, _write, INA3221_REG_CONF, INA3221::conf_reg_t::mode_shunt_en.
void INA3221::setBusMeasEnable()
References _read, _write, INA3221_REG_CONF, INA3221::conf_reg_t::mode_bus_en.
void INA3221::setBusMeasDisable()
References _read, _write, INA3221_REG_CONF, INA3221::conf_reg_t::mode_bus_en.
void INA3221::setAveragingMode(ina3221_avg_mode_t mode)
References _read, _write, INA3221::conf_reg_t::avg_mode, INA3221_REG_CONF.
void INA3221::setBusConversionTime(ina3221_conv_time_t convTime)
References _read, _write, INA3221::conf_reg_t::bus_conv_time, INA3221_REG_CONF.
void INA3221::setShuntConversionTime(ina3221_conv_time_t convTime)
References _read, _write, INA3221_REG_CONF, INA3221::conf_reg_t::shunt_conv_time.
void INA3221::setCritAlertLimit(ina3221_ch_t channel, int32_t voltageuV)
void INA3221::setWarnAlertLimit(ina3221_ch_t channel, int32_t voltageuV)
void INA3221::setPwrValidUpLimit(int16_t voltagemV)
void INA3221::setPwrValidLowLimit(int16_t voltagemV)
void INA3221::setShuntSumAlertLimit(int32_t voltagemV)
void INA3221::setCurrentSumAlertLimit(int32_t currentmA)
void INA3221::setWarnAlertLatchEnable()
void INA3221::setWarnAlertLatchDisable()
void INA3221::setCritAlertLatchEnable()
void INA3221::setCritAlertLatchDisable()
void INA3221::readFlags()
bool INA3221::getTimingCtrlAlertFlag()
bool INA3221::getPwrValidAlertFlag()
bool INA3221::getCurrentSumAlertFlag()
bool INA3221::getConversionReadyFlag()
uint16_t INA3221::getManufID()
References _read, id, INA3221_REG_MANUF_ID.
Referenced by begin.
uint16_t INA3221::getDieID()
References _read, id, INA3221_REG_DIE_ID.
Referenced by begin.
void INA3221::setChannelEnable(ina3221_ch_t channel)
void INA3221::setChannelDisable(ina3221_ch_t channel)
void INA3221::setWarnAlertShuntLimit(ina3221_ch_t channel, int32_t voltageuV)
void INA3221::setCritAlertShuntLimit(ina3221_ch_t channel, int32_t voltageuV)
void INA3221::setWarnAlertCurrentLimit(ina3221_ch_t channel, int32_t currentmA)
void INA3221::setCritAlertCurrentLimit(ina3221_ch_t channel, int32_t currentmA)
void INA3221::setCurrentSumEnable(ina3221_ch_t channel)
void INA3221::setCurrentSumDisable(ina3221_ch_t channel)
int32_t INA3221::getShuntVoltage(ina3221_ch_t channel)
References _read, INA3221_CH1, INA3221_CH2, INA3221_CH3, INA3221_REG_CH1_SHUNTV, INA3221_REG_CH2_SHUNTV, INA3221_REG_CH3_SHUNTV, SHUNT_VOLTAGE_LSB_UV.
Referenced by getCurrent, getCurrent_mA, getCurrentCompensated, getCurrentCompensated_mA.
bool INA3221::getWarnAlertFlag(ina3221_ch_t channel)
bool INA3221::getCritAlertFlag(ina3221_ch_t channel)
int32_t INA3221::estimateOffsetVoltage(ina3221_ch_t channel, uint32_t busVoltage)
References _filterRes, _shuntRes.
Referenced by getCurrentCompensated, getCurrentCompensated_mA.
float INA3221::getCurrent(ina3221_ch_t channel)
References _shuntRes, getShuntVoltage.
float INA3221::getCurrent_mA(ina3221_ch_t channel)
References _shuntRes, getShuntVoltage.
float INA3221::getCurrentCompensated(ina3221_ch_t channel)
References _shuntRes, estimateOffsetVoltage, getShuntVoltage, getVoltage.
float INA3221::getCurrentCompensated_mA(ina3221_ch_t channel)
References _shuntRes, estimateOffsetVoltage, getShuntVoltage, getVoltage.
float INA3221::getVoltage(ina3221_ch_t channel)
References _read, INA3221_CH1, INA3221_CH2, INA3221_CH3, INA3221_REG_CH1_BUSV, INA3221_REG_CH2_BUSV, INA3221_REG_CH3_BUSV.
Referenced by getCurrentCompensated, getCurrentCompensated_mA.