communication.h
bool initializeRadio()
References COMMS, csPin, EventEmitter::emit, irqPin, LoRa, RADIO_ERROR, RADIO_INIT, resetPin, uartPrint.
Referenced by main.
void sendMessage(std::string outgoing)
References outgoing.
Referenced by main.
void sendLargePacket(const uint8_t *data, size_t length)
References LoRa.
void onReceive(int packetSize)
References buffer, destination, FRAME_BEGIN, FRAME_END, localAddress, LoRa, processFrameData, uartPrint.
Referenced by main.
void handleUartInput()
References DEBUG_UART_PORT, processFrameData, uartPrint.
Referenced by main.
void processFrameData(const std::string &data)
Execute the command based on the command key and the parameter.
data Frame data in string format
References buildFrame, Frame::command, decodeFrame, ERROR, executeCommand, Frame::group, Frame::operationType, sendFrame, Frame::value.
Referenced by handleUartInput, onReceive.
void handleCommandFrame(const Frame &frame)
References group, UNDEFINED.
Frame executeCommand(uint32_t commandKey, const std::string &param, OperationType operationType)
References buildFrame, commandHandlers, ERROR.
Referenced by processFrameData.
void sendEventRegister()
Send event register value to the ground station.
This function is called in the main loop
References buildFrame, eventRegister, sendFrame, SUCCESS.
std::string encodeFrame(const Frame &frame)
Encode Frame instance into a string.
frame Frame instance to encode Frame encoded as a string
References Frame::command, DELIMITER, Frame::direction, FRAME_BEGIN, FRAME_END, Frame::group, Frame::operationType, operationTypeToString, Frame::unit, Frame::value.
Referenced by sendFrame.
Frame decodeFrame(const std::string &data)
Convert a string into a Frame instance.
data Frame data as a string Frame instance
References buildFrame, Frame::command, DELIMITER, Frame::direction, ERROR, FRAME_BEGIN, FRAME_END, Frame::group, Frame::header, Frame::operationType, sendFrame, stringToOperationType, uartPrint, Frame::unit, Frame::value.
Referenced by processFrameData.
Frame buildFrame(ExecutionResult result, uint8_t group, uint8_t command, const std::string &value, const ValueUnit unitType=ValueUnit::UNDEFINED)
References ANS, Frame::command, Frame::direction, ERR, ERROR, Frame::footer, FRAME_BEGIN, FRAME_END, Frame::group, group, Frame::header, INF, INFO, Frame::operationType, SUCCESS, UNDEFINED, Frame::unit, Frame::value, valueUnitTypeToString.
Referenced by decodeFrame, executeCommand, handleEnableGPSTransparentMode, handleEnterBootloaderMode, handleGetBuildVersion, handleGetClockDrift, handleGetClockSyncInterval, handleGetCurrentChargeSolar, handleGetCurrentChargeTotal, handleGetCurrentChargeUSB, handleGetCurrentDraw, handleGetEventCount, handleGetGGAData, handleGetLastEvents, handleGetLastSyncTime, handleGetPowerManagerIDs, handleGetRMCData, handleGetTimezoneOffset, handleGetVoltage5V, handleGetVoltageBattery, handleGPSPowerStatus, handleListCommands, handleSetClockDrift, handleSetClockSyncInterval, handleSetTimezoneOffset, handleTime, initSystems, main, processFrameData, sendEventRegister.
std::string determineUnit(uint8_t group, uint8_t command)
References group, outgoing.
void sendFrame(const Frame &frame)
References encodeFrame, sendMessage.
Referenced by decodeFrame, handleEnterBootloaderMode, initSystems, main, processFrameData, sendEventRegister.