frame.cpp
using CommandHandler = std::function<std::string(const std::string&, OperationType)>
std::map<uint32_t, CommandHandler> commandHandlers
Referenced by executeCommand, handleGetCommandsTimestamp, handleListCommands.
volatile uint16_t eventRegister
Referenced by sendEventRegister.
std::string encodeFrame(const Frame &frame)
Encode Frame instance into a string.
frame Frame instance to encode Frame encoded as a string
References Frame::command, DELIMITER, Frame::direction, FRAME_BEGIN, FRAME_END, Frame::group, Frame::operationType, operationTypeToString, Frame::unit, Frame::value.
Referenced by sendFrame.
Frame decodeFrame(const std::string &data)
Convert a string into a Frame instance.
data Frame data as a string Frame instance
References buildFrame, Frame::command, DELIMITER, Frame::direction, ERROR, FRAME_BEGIN, FRAME_END, Frame::group, Frame::header, Frame::operationType, sendFrame, stringToOperationType, uartPrint, Frame::unit, Frame::value.
Referenced by processFrameData.
void processFrameData(const std::string &data)
Execute the command based on the command key and the parameter.
data Frame data in string format
References buildFrame, Frame::command, decodeFrame, ERROR, executeCommand, Frame::group, Frame::operationType, sendFrame, Frame::value.
Referenced by handleUartInput, onReceive.
void sendEventRegister()
Send event register value to the ground station.
This function is called in the main loop
References buildFrame, eventRegister, sendFrame, SUCCESS.
Frame buildFrame(ExecutionResult result, uint8_t group, uint8_t command, const std::string &value, const ValueUnit unitType)
References ANS, Frame::command, Frame::direction, ERR, ERROR, Frame::footer, FRAME_BEGIN, FRAME_END, Frame::group, group, Frame::header, INF, INFO, Frame::operationType, SUCCESS, UNDEFINED, Frame::unit, Frame::value, valueUnitTypeToString.
Referenced by decodeFrame, executeCommand, handleEnableGPSTransparentMode, handleEnterBootloaderMode, handleGetBuildVersion, handleGetClockDrift, handleGetClockSyncInterval, handleGetCurrentChargeSolar, handleGetCurrentChargeTotal, handleGetCurrentChargeUSB, handleGetCurrentDraw, handleGetEventCount, handleGetGGAData, handleGetLastEvents, handleGetLastSyncTime, handleGetPowerManagerIDs, handleGetRMCData, handleGetTimezoneOffset, handleGetVoltage5V, handleGetVoltageBattery, handleGPSPowerStatus, handleListCommands, handleSetClockDrift, handleSetClockSyncInterval, handleSetTimezoneOffset, handleTime, initSystems, main, processFrameData, sendEventRegister.