protocol.h
ExecutionResult
OperationType
CommandAccessLevel
ValueUnit
ExceptionType
const std::string FRAME_BEGIN
Referenced by buildFrame, decodeFrame, encodeFrame, onReceive.
const std::string FRAME_END
Referenced by buildFrame, decodeFrame, encodeFrame, onReceive.
const char DELIMITER
Referenced by decodeFrame, encodeFrame.
std::string exceptionTypeToString(ExceptionType type)
References INVALID_OPERATION, INVALID_PARAM, NONE, NOT_ALLOWED, PARAM_UNECESSARY.
std::string operationTypeToString(OperationType type)
References ANS, ERR, GET, INF, SET.
Referenced by encodeFrame.
OperationType stringToOperationType(const std::string &str)
References ANS, ERR, GET, INF, SET.
Referenced by decodeFrame.
std::vector< uint8_t > hexStringToBytes(const std::string &hexString)
Convert a hex string to a vector of bytes.
hexString Hex string to convert Vector of bytes
std::string valueUnitTypeToString(ValueUnit unit)
References BOOL, DATETIME, MILIAMP, SECOND, TEXT, UNDEFINED, VOLT.
Referenced by buildFrame.