send.cpp
void sendMessage(string outgoing)
References destination, localAddress, LoRa, outgoing, uartPrint.
Referenced by sendFrame.
void sendFrame(const Frame &frame)
References encodeFrame, sendMessage.
Referenced by decodeFrame, handleEnterBootloaderMode, initSystems, main, processFrameData, sendEventRegister.
void sendLargePacket(const uint8_t *data, size_t length)
References LoRa.