utils.cpp
LOG_FILENAME
mutex_t uart_mutex
Referenced by uartPrint.
void uartPrint(const std::string &msg, bool logToFile, uart_inst_t *uart)
References timestamp, uart_mutex.
Referenced by INA3221::begin, checkPowerEvents, collectGPSData, decodeFrame, handleEnableGPSTransparentMode, handleEnterBootloaderMode, handleGetCurrentChargeSolar, handleGetCurrentChargeTotal, handleGetCurrentChargeUSB, handleGetCurrentDraw, handleGetVoltage5V, handleGetVoltageBattery, handleListCommands, handleUartInput, initializeRadio, initSystems, EventManager::logEvent, loggingRoutine, main, onReceive, sendMessage.
uint16_t crc16(const uint8_t *data, size_t length)