utils_converters.cpp
std::string exceptionTypeToString(ExceptionType type)
References INVALID_OPERATION, INVALID_PARAM, NONE, NOT_ALLOWED, PARAM_UNECESSARY.
std::string valueUnitTypeToString(ValueUnit unit)
References BOOL, DATETIME, MILIAMP, SECOND, TEXT, UNDEFINED, VOLT.
Referenced by buildFrame.
std::string operationTypeToString(OperationType type)
References ANS, ERR, GET, INF, SET.
Referenced by encodeFrame.
OperationType stringToOperationType(const std::string &str)
References ANS, ERR, GET, INF, SET.
Referenced by decodeFrame.
std::vector< uint8_t > hexStringToBytes(const std::string &hexString)
Convert a hex string to a vector of bytes.
hexString Hex string to convert Vector of bytes